name: animate-frames
version: '0.0.1'
github: "jxv/animate-frames"
license: MIT
author: "Joe Vargas"
maintainer: "Joe Vargas"
description: Convert sprite frames to animate files
synopsis: Convert sprite frames to animate files
category: Game

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yam
- propagada/animate-preview.png
- propagada/compile-frames.sh
- propagada/dance_krita.png
- propagada/dance_render.png
- propagada/dance.kra
- propagada/figure.png
- propagada/figure.yaml
- propagada/frames.png
- propagada/wall_krita.png
- propagada/wall_render.png
- propagada/wall.kra

ghc-options: -Wall

default-extensions:
- NamedFieldPuns
- OverloadedStrings
- FlexibleContexts

library:
  dependencies:
  - aeson
  - async
  - base >= 4.5 && <5
  - bytestring
  - animate
  - JuicyPixels
  - yaml
  - containers
  - pureMD5
  - safe
  - text
  - vector
  - stm
  source-dirs: library

executables:
  animate-frames:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - animate-frames
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  animate-frames-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - animate-frames
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
