name: animate-frames
version: '0.0.2'
github: "jxv/animate-frames"
license: MIT
author: "Joe Vargas"
maintainer: "Joe Vargas"
description: Convert sprite frames to animate files
synopsis: Convert sprite frames to animate files
category: Game

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yam
- propaganda/animate-preview.png
- propaganda/compile-frames.sh
- propaganda/dance_krita.png
- propaganda/dance_render.png
- propaganda/dance.kra
- propaganda/figure.png
- propaganda/figure.yaml
- propaganda/frames.png
- propaganda/walk_krita.png
- propaganda/walk_render.png
- propaganda/walk.kra

ghc-options: -Wall

default-extensions:
- NamedFieldPuns
- OverloadedStrings
- FlexibleContexts

library:
  dependencies:
  - aeson
  - async
  - base >= 4.5 && <5
  - bytestring
  - animate
  - JuicyPixels
  - yaml
  - containers
  - safe
  - text
  - vector
  - stm
  - cryptohash-sha256
  source-dirs: library

executables:
  animate-frames:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - animate-frames
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  animate-frames-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - animate-frames
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
